import SmartCommunityFeed from '../components/community/SmartCommunityFeed';

// Existing code...

{activeTab === 'feed-inteligente' && !viewingProfileId && (<SmartCommunityFeed user={user} profile={profile} onViewProfile={setViewingProfileId} />)}
// Existing code...